name: "server shell"
description: "action for app deployment with ssh"
author: "tzzs"
branding:
  icon: 'server'
  color: 'blue'
inputs:
  PRIVATE_KEY:
    description: "server private key"
    required: true
  USERNAME:
    description: "server login username"
    required: true
  IP:
    description: "server ip"
    required: true
  SHELL:
    description: "shell to execute on server"
    required: false

runs:
  using: "node12"
  main: "dist/index.js"
